name: zoomdrive
description: GitHub action to download Zoom recordings periodically and upload to Google Drive
author: "Open Healthcare Network"

inputs:
  zoom-account-id:
    description: Zoom Account ID
    required: true

  zoom-client-id:
    description: Client ID of Zoom OAuth App
    required: true

  zoom-client-secret:
    description: Client Secret of Zoom OAuth App
    required: true

  zoom-user-id:
    description: Zoom User ID
    required: false
    default: me

  meeting-id:
    description: Zoom Meeting ID
    required: false

  lookback-days:
    description: Number of days to keep Zoom meeting recordings
    required: false
    default: "7"

  end-date:
    description: End date of Zoom meeting recordings to keep
    required: false

  delete-on-success:
    description: Delete Zoom files after uploading to Google Drive
    required: false
    default: "false"

  gsa-credentials:
    description: Google Service Account Credentials
    required: true

  meeting-gdrive-folder-map:
    description: JSON Map of meeting ID to folder ID
    required: true
    default: "{}"

outputs:
  result:
    description: The result of the action

runs:
  using: node16
  main: dist/index.js
